### ISSUE TITLE
Bot will not connect with second factor

### ISSUE THREAD

**Issue by pascalo7** [omegavesko/DiscordAnimeStatus#1]
When i have second factor enabled the bot will not connect to my account, is there a way you could have the bot request for the user to input the code on first time launch so it can connect?

**Comment by lynnntropy** [comment]
Unfortunately, Discord.Net has [decided against supporting 2FA](https://github.com/RogueException/Discord.Net/issues/68), so there isn't much I can immediately do about this.

**Comment by pascalo7** [comment]
ah, ok. Thanks anyway <3

**Comment by vladfrangu** [comment]
You could always use the token, I'm guessing. From what I've read, you can use the local token (CTRL / CMD + shitft + I, Console, `localStorage.token`), instead of always logging in.
