### ISSUE TITLE
What did you add in status

### ISSUE THREAD

**Issue by doublear** [omegavesko/DiscordAnimeStatus#2]
How does this I am curious how this thing work. what did you put for game status in discord?

is it this program or Taiga?

**Comment by lynnntropy** [comment]
Sorry, I'm not sure what you mean. The way it works is that it accepts the status update as a JSON object from Taiga over HTTP, parses it into a C# object (`RequestModel.cs`), and then uses Discord.Net to set your Discord status to the output of `RequestModel.ToStatusString()`.

**Comment by doublear** [comment]
I am talking about this screen
http://puu.sh/r9Z0j/d5a4a469be.jpg

what do you put?

**Comment by lynnntropy** [comment]
Ah, you don't use it like that. DiscordAnimeStatus logs into your account directly and sets your status, you don't need to set anything up in the desktop app.

Just follow the steps in the readme.

**Comment by doublear** [comment]
oh i got it now, thanks
